name: 'Extract Jira Ticket ID'
description: 'Extracts Jira Ticket ID from PR title, branch name, or commit messages'
branding:
  icon: 'check-circle'
  color: 'green'
outputs:
  jira_ticket_id:
    description: 'The extracted Jira Ticket ID'
    value: ${{ steps.extract_jira_ticket_id.outputs.jira_ticket_id }}
runs:
  using: 'composite'
  steps:
    - name: Extract Jira Ticket ID
      id: extract_jira_ticket_id
      run: |
        set +e
        set +o pipefail

        jira_ticket_id=""
        
        # Check PR title
        if [[ ${{ github.event_name }} == 'pull_request' ]]; then
          jira_ticket_id=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]+-[0-9]+')
        fi

        # Check branch name
        if [[ -z $jira_ticket_id ]]; then
          jira_ticket_id=$(echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | grep -oE '[A-Z]+-[0-9]+')
        fi

        if [[ -z $jira_ticket_id ]]; then
          echo "No Jira Ticket ID found"
        else
          echo "Jira Ticket ID: $jira_ticket_id"
          echo "jira_ticket_id=$(echo $jira_ticket_id)" >> $GITHUB_OUTPUT
        fi
      shell: bash