name: 'Extract Jira Ticket ID'
description: 'Extracts Jira Ticket ID from PR title, branch name, or commit messages'
branding:
  icon: 'check-circle'
  color: 'green'
outputs:
  jira_ticket_id:
    description: 'The extracted Jira Ticket ID'
runs:
  using: 'composite'
  steps:
    - run: |
        jira_ticket_id=""
        # Check PR title
        if [[ ${{ github.event_name }} == 'pull_request' ]]; then
          jira_ticket_id=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]+-[0-9]+')
        fi

        echo "First step passed"

        # Check branch name
        if [[ -z $jira_ticket_id ]]; then
          echo "Jira ticket: $jira_ticket_id"
          jira_ticket_id=$(echo "${{ github.ref }}" | grep -oE '[A-Z]+-[0-9]+')
          echo "We are here! $jira_ticket_id"
        fi

        echo "Second step passed"

        # Check commit messages
        if [[ -z $jira_ticket_id ]]; then
          jira_ticket_id=$(git log --format=%B -n 1 | grep -oE '[A-Z]+-[0-9]+')
        fi

        echo "Third step passed"

        if [[ -z $jira_ticket_id ]]; then
          echo "No Jira Ticket ID found"
        else
          echo "Jira Ticket ID: $jira_ticket_id"
          echo "jira_ticket_id=$jira_ticket_id" >> "$GITHUB_OUTPUT"
        fi
      shell: bash